### ISSUE TITLE
Add support for creating events

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry-holding/edgex-cli#100]
# 🚀 Feature Request

### Description

Add functionality for creating events.

I am making a big request here and I think that this solution can possibly be applied to other entities. 

### Describe the solution you'd like
Create a new `create` command for the `event` sub-command which creates new events in EdgeX. The issue with events is that it contains a lot of information which we cannot expect the user to provide cleanly via the command line. I think we can use an editor like vi(m) and provide a template for the user to populate which then can be used to create the event. A good example of this is how `git` handles interactive rebase and commit messages(without the `-m`). 

Some other nice feature that would be cool:

1. Allow the user to set their preferred editor in some global way. Like how you can configure it with `git`
2. Allow the user to provide some optional information via flags that will populate some of the fields in the template. This would be useful if someone wants to pipe commands together and use existing information like timestamps.
3. Allow the user to re-edit their changes if there is an error sending the information to EdgeX. For example, if I mistype something which results in a 400(Bad request), it would be nice to be able to fix the issue without re-typing everything especially since piped information can be lost.

### Describe alternatives you've considered
Allow the user to provide the information via flags and/or arguments. I decided to not go this route for ease of use as there is too much information to be provided via CLI.

**Comment by couralex6** [comment]
Sorry for the late response @AnthonyMBonafide .

I think this is a great idea that could be used for any `add` command across the CLI.

I'll add this as a deliverable for Geneva.
