### ISSUE TITLE
Mike's Feedback before merging

### ISSUE THREAD

**Issue by rsdmike** [edgexfoundry-holding/edgex-cli#114]
This will house my feedback given that there can't be a PR to the main organization. Will be updated as I review. 

## Licensing:

a little suspect is https://github.com/ghodss/yaml -- which is MIT w/ Go Authors copyright attached. We are using gopkg.in/yaml.v2 in edgex-go, what does the ghodss/yaml pkg do that the one we are using doesnt would be my question.
 The rest of the go.mod dependencies are already in use with EdgeX -- so didnt concern myself too much with them. 

| Dependency | LICENSE |
|------|----|
| github.com/BurntSushi/toml v0.3.1 | MIT |
| github.com/edgexfoundry/go-mod-core-contracts v0.1.3|  Apache-2.0 |
| github.com/ghodss/yaml v1.0.0| MIT-ish |
| github.com/pelletier/go-toml v1.2.0| MIT |
| github.com/spf13/afero v1.1.2| Apache-2.0 |
| github.com/spf13/cobra v0.0.5| Apache-2.0 |
| github.com/spf13/viper v1.3.2| Apache-2.0 |
| github.com/stretchr/testify v1.3.0| MIT  |

Would like to have replace removed:
https://github.com/edgexfoundry-holding/edgex-cli/blob/40e914d7f567781df4c71cea0a0dd6ca029a088f/go.mod#L14

## Code Review:
See Individual Comments
## General Feedback:
I've taken a look across the cli and its code and my biggest concerns are (in priority order):

- maintainability
- error handling
- configuration
- consistency across commands

I'm not saying ALL of these things need to be done before moving, but I think the hardcoded values of all the paths and ports need to leverage go mod core contracts before moving-- it will make it easier in the future to move to API V2. Other than the listed issues, i don't see any other major concerns that should prevent the movement. I would suggest to swap the default of the commands to NOT use `pager` for lists and to use a flag `--pager` to indicate if you want to use it -- this will make the windows compatibility issues less of a concern.

**Comment by rsdmike** [comment]
https://github.com/edgexfoundry-holding/edgex-cli/blob/40e914d7f567781df4c71cea0a0dd6ca029a088f/cmd/status/status.go#L62

Any REST Request path should leverage the routes defined in go-mod-core-contracts. Will help with maintaibility: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/clients/constants.go

**Comment by rsdmike** [comment]
Ideally these ports should be defined in a config (with these defaults set) and leveraged everywhere through the application. 

https://github.com/edgexfoundry-holding/edgex-cli/blob/40e914d7f567781df4c71cea0a0dd6ca029a088f/cmd/status/status.go#L48

This is especially needed for docker deployments since it is common to change the port exposed to the host to avoid conflicts with existing software on machines.

**Comment by rsdmike** [comment]
Any reference to Export Services/Client Registration should be removed as it has been removed for Geneva. We will probably have to figure out best way to manage (if needed) App Service Configurable
https://github.com/edgexfoundry-holding/edgex-cli/blob/40e914d7f567781df4c71cea0a0dd6ca029a088f/cmd/status/status.go#L55

**Comment by rsdmike** [comment]
The path doesn't look correct for getting version? Shouldn't it be `/api/version`? Also should leverage go-mod-core-contracts constant as mentioned above.
https://github.com/edgexfoundry-holding/edgex-cli/blob/40e914d7f567781df4c71cea0a0dd6ca029a088f/pkg/client.go#L184
running `.\edgex-cli.exe version` yields the following output:
```
edgex-cli version: 0.0.1
version:  404 page not found
```
The comment in client.go says it will print version for all services, but i only see the above output -- not clear as to what version should be reported.

**Comment by rsdmike** [comment]
Pushed shouldn't read 50 Years -- should be either true/false or blank when not pushed and the date it was pushed if its filled in. 

```
PS C:\Development\intel\edgex-cli> .\edgex-cli.exe -v  reading list
Reading ID                              Name    Device                          Origin                  Value                   Created Modified        Pushed
2ef0fead-0f63-4630-9ed5-ef58d7d1f9eb    Bool    Random-Boolean-Device           1579636022041088000     false                   2 weeks 2 weeks         50 years
29d00f63-07b1-4fed-92dd-257dcb1cd3d6    Bool    Random-Boolean-Device           1579636022011768100     true                    2 weeks 2 weeks         50 years
```

**Comment by rsdmike** [comment]
`list` subcommand doesn't seem to work without -v or -- no-pager on Windows:
```
PS C:\Development\intel\edgex-cli> .\edgex-cli.exe device list
write |1: file already closed
PS C:\Development\intel\edgex-cli> .\edgex-cli.exe deviceservice list
PS C:\Development\intel\edgex-cli> .\edgex-cli.exe event list        
PS C:\Development\intel\edgex-cli> .\edgex-cli.exe reading list
PS C:\Development\intel\edgex-cli> .\edgex-cli.exe addressable list
write |1: file already closed
PS C:\Development\intel\edgex-cli> .\edgex-cli.exe addressable list -v
HEADER
Content-Type : [application/json]
Date : [Tue, 21 Jan 2020 19:51:14 GMT]
Content-Length : [354]
BODY
[{"created":1576005060115,"modified":1576005060115,"origin":1576005060115,"id":"bf65d2ac-6d29-474e-bf3d-8d1cc57c637c","name":"device-virtual","protocol":"HTTP","method":"POST","address":"edgex-device-virtual","port":49990,"path":"/api/v1/callback","baseURL":"http://edgex-device-virtual:49990","url":"http://edgex-device-virtual:49990/api/v1/callback"}]
```

```
PS C:\Development\intel\edgex-cli> .\edgex-cli.exe addressable list --no-pager
ID                                      Name            Protocol
bf65d2ac-6d29-474e-bf3d-8d1cc57c637c    device-virtual  HTTP
PS C:\Development\intel\edgex-cli> 
```

**Comment by rsdmike** [comment]
command `reading list` with `-v` doesn't print HTTP response per the command documentation. See above comments -- `reading list -v` prints a table, while `addressable list -v` prints an HTTP Response (as expected).

**Comment by rsdmike** [comment]
Why does `notification` command not have a subcommand for `list`?

**Comment by rsdmike** [comment]
Unsure why 24H is in invalid frequency -- its the the default in EdgeX. 
```
PS C:\Development\intel\edgex-cli> .\edgex-cli.exe interval list
http://localhost:48085/api/v1/interval
invalid Interval Frequency 24h
PS C:\Development\intel\edgex-cli> 
```
HTTP Response:
[{"Timestamps":{"created":1576005058483,"modified":1576005058483},"id":"e4895868-65e6-4346-8be0-74342e557213","name":"midnight","start":"20180101T000000","frequency":"24h"}]

**Comment by rsdmike** [comment]
```
 .\edgex-cli.exe device add   
Add Devices:
```
Indication that I am missing flags, or in this case a file is not provided/or found should be indicated.

**Comment by rsdmike** [comment]
> https://github.com/edgexfoundry-holding/edgex-cli/blob/40e914d7f567781df4c71cea0a0dd6ca029a088f/cmd/status/status.go#L62
> 
> Any REST Request path should leverage the routes defined in go-mod-core-contracts. Will help with maintainability: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/clients/constants.go.
> 
> Also, can the clients in the go-mod-core-contracts be used instead of having to recreate the REST request?

Still think theres a little more work to be done here: 
![image](https://user-images.githubusercontent.com/22204562/77694077-adb6b100-6f66-11ea-9c98-fc5a594c5db3.png)

**Comment by difince** [comment]
All the concerns here have been addressed by fixing dedicated issues. See issues list here:  
https://github.com/edgexfoundry-holding/edgex-cli/issues?q=is%3Aissue+Mike+is%3Aclosed
