### ISSUE TITLE
Display events

### ISSUE THREAD

**Issue by alexcourouble** [edgexfoundry-holding/edgex-cli#12]
Display all events and for given device.

**Comment by alexcourouble** [comment]
Hey @nkstanchev, want to try working on this? We can zoom to chat about it if you'd like!

**Comment by nkstanchev** [comment]
@alexcourouble Sure! Count me in

**Comment by alexcourouble** [comment]
@nkstanchev for now, we can just implement a `list` subcommand under `event`. You can look at the other `list` subcommands as an example. We can use this API call:  `http://localhost:48080/api/v1/event`.

In the future, we can imagine list the events just for a specific device. In this case, the command would look like this: `edgex event list [DEVICE NAME/ID]`. But no rush :) 

Let me know if you have any issues!
