### ISSUE TITLE
Mike-Bug: Docs claim CLI will provide individual service version information

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry-holding/edgex-cli#125]
# 📚 Docs Bug Report

### Description
The comment in client.go says it will print version for all services, but i only see the above output -- not clear as to what version should be reported.
### What's the affected URL?**
running 
> .\edgex-cli.exe version

The command certainly does not take a service name today.
This may not be important at this point. Fix the docs to reflect the actual implementation.
This service level version might be useful with our ancillary services such as Device SDK and App function SDK that can move independently.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

Mac Fuji EdgeX

**Comment by difince** [comment]
Documentation match the implantation. 
Printing version of  Device SDK and App function SDK is for future
