### ISSUE TITLE
Mike-Bug: Command Reading List with -v does not match documented behaviour

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry-holding/edgex-cli#128]
# 🐞 Bug Report

### Affected Command
command reading list with -v doesn't print HTTP response per the command documentation. See above comments -- reading list -v prints a table, while addressable list -v prints an HTTP Response (as expected). For reading command, -u doesn't print URL as well.
### Is this a regression?

No
## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

EdgeX Fuji

**Anything else relevant?**

**Comment by difince** [comment]
Currently, all list commands including reading list, prints the results in json format. (see PR https://github.com/edgexfoundry-holding/edgex-cli/pull/214)
Commands that use go-mod-core-contracts interface for creating curl requests, does not print the URL. Another more generic issue will be created
