### ISSUE TITLE
Mike-Bug: 24 hrs/a day is considered an invalid interval

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry-holding/edgex-cli#130]
# 🐞 Bug Report

### Affected Command
Unsure why 24H is in invalid frequency -- its the default in EdgeX.

PS C:\Development\intel\edgex-cli> .\edgex-cli.exe interval list
http://localhost:48085/api/v1/interval
invalid Interval Frequency 24h
PS C:\Development\intel\edgex-cli> 
HTTP Response:

[{"Timestamps":{"created":1576005058483,"modified":1576005058483},"id":"e4895868-65e6-43
### Is this a regression?

No
## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

EdgeX Fuji

**Anything else relevant?**

**Comment by difince** [comment]
The error `invalid Interval Frequency 24h` does not come from the CLI, but from  go-mod-core-contracts Interval.Validate method: 
https://github.com/edgexfoundry/go-mod-core-contracts/blob/38d0cc147a837ce191fd6fcb9b0683ab407438b4/models/interval.go#L136-L150
As I see `24H` is really not valid format. Instead `24h` should be used.

```
./edgex-cli interval update samples/updateInterval.json
Error occur:  invalid Interval frequency 24H format


./edgex-cli interval list
Interval ID                             Name                    Start           End     Frequency       Cron    RunOnce 
3a6ee391-8210-4bbb-8fca-0fc77d21f5d4    midnight                20180101T000000         24h                     false   
c1d02a4d-ad56-42ac-bc8a-fed27fb8ff40    noon                    20180101T000000         24h                     false   
1c04a4ac-5f19-4efe-8e87-e532144812ac    fourteen-hundrend-hours 20180101T000000         P4D                     false   

```

At that moment I do not see a problem. Is it is wanted 24H to be supported as well an issue in go-mod-core-contracts need to be opened
