### ISSUE TITLE
Mike-Bug: Inadequate error feedback in device context

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry-holding/edgex-cli#131]
# 🐞 Bug Report

### Affected Command
 .\edgex-cli.exe device add   
Add Devices:

Indication that I am missing flags, or in this case a file is not provided/or found should be indicated.
### Is this a regression?

No
## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

EdgeX Fuji

**Anything else relevant?**

**Comment by difince** [comment]
fixed by OR #144
