### ISSUE TITLE
Mike-Bug: Use Go-Mod-Contracts for ease of maintainability

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry-holding/edgex-cli#134]
# 🐞 Bug Report
Any REST Request path should leverage the routes defined in go-mod-core-contracts. Will help with maintainability: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/clients/constants.go.

Also, can the clients in the go-mod-core-contracts be used instead of having to recreate the REST request?
example:
 resp, err := http.Get("http://" + host + ":" + port + "/api/v1/ping") 

Let us also list those that are not currently support in go-mod-contracts, and leave them as to-do future items.
See https://user-images.githubusercontent.com/22204562/77694077-adb6b100-6f66-11ea-9c98-fc5a594c5db3.png
### Affected Command

 The issue is located in: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

EdgeX Fuji:**

**Anything else relevant?**

**Comment by difince** [comment]
Addressed in https://github.com/edgexfoundry-holding/edgex-cli/pull/152
