### ISSUE TITLE
Mike-Bug: Remove references to the deprecated entity Client Registration

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry-holding/edgex-cli#136]
# 🐞 Bug Report

### Affected Command
Any reference to Export Services/Client Registration should be removed as it has been removed for Geneva. We will probably have to figure out best way to manage (if needed) App Service Configurable

edgex-cli/cmd/status/status.go
Line 55 in 40e914d
 microservices["Client Registration"] = "48071" 
 The issue is located in: 

### Is this a regression?

No
## 🔥 Exception or Error

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

EdgeX Fuji

**Anything else relevant?**

**Comment by difince** [comment]
addressed https://github.com/edgexfoundry-holding/edgex-cli/pull/152
Still need to figure out best way to manage (if needed) App Service Configurable
