### ISSUE TITLE
Fix Configuration tests 

### ISSUE THREAD

**Issue by difince** [edgexfoundry-holding/edgex-cli#142]
# 🐞 Bug Report
File [configuration_test.go](https://github.com/edgexfoundry-holding/edgex-cli/blob/master/config/configuration_test.go) fail to compile. 
### Affected Command
None

### Is this a regression?
Yes
Changes done in [Configuration](https://github.com/edgexfoundry-holding/edgex-cli/blob/aa74bdf6f371f26a315c80fd2ec7906a80510907/config/configuration.go#L28) struct leads to compilation error in the [TestConf](https://github.com/edgexfoundry-holding/edgex-cli/blob/aa74bdf6f371f26a315c80fd2ec7906a80510907/config/configuration_test.go#L34)

Update `TestConf` to address the changes already done in the other file. Ensure all Configuration tests pass successfully   

## 🔥 Exception or Error
https://github.com/edgexfoundry-holding/edgex-cli/blob/aa74bdf6f371f26a315c80fd2ec7906a80510907/config/configuration_test.go#L34-L72
All paths inside `TestConf` structure does not exists anymore. (Like `IntervalByNameSlugRoute:       "interval/name/"` ) It leads to compilation error and failed tests. 

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by mkbhanda** [comment]
We can start off my dropping the config/testdata/config.yaml file and re-using the res/configuration.toml file @difince recently introduced. The paths will need to be reconstructed in the calls. Oh well.
