### ISSUE TITLE
configurable locations for core-metadata and other services

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry-holding/edgex-cli#16]
localhost:48081 is ok as a default for core-metadata but it should be possible to set something different.
Could be an option `--metadata=edgex-core-metadata:48081`
or an environment variable `export EDGEX_METADATA=edgex-core-metadata:48081`
or we have a settings file somewhere with core-data/core-metadata/registry/whatever else
or some combination

**Comment by alexcourouble** [comment]
We could create a config file: `~/.edgex-cli-config.yml` containing all the configurable variables (we'll probably have a lot more in the future). I could take this.

**Comment by alexcourouble** [comment]
Unless you already had something in mind. If so feel free to take it
