### ISSUE TITLE
List commands should return correct error message in case of  excess data

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry-holding/edgex-cli#163]
# 🐞 Bug Report

### Affected Command
List commands should return correct error message in case of  excess data
./edgex-cli readings list

 The issue is located in: 

### Is this a regression?
No
Happens when too many readings and events in a system.

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by difince** [comment]
Already fix by @mkbhanda in PR https://github.com/edgexfoundry-holding/edgex-cli/pull/165
