### ISSUE TITLE
Match Edgex-cli executable name with the usage help presented

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry-holding/edgex-cli#179]
# 🐞 Bug Report

### Affected Command
./edgex-cli help 
shows
 ______     _              __   __            _____  _       _____        
|  ____|   | |             \ \ / /           / ____|| |     |_   _|     
| |__    __| |  __ _   ___  \ V /   ______  | |     | |       | |        
|  __|  / _` | / _` | / _ \  > <   |______| | |     | |       | |        
| |____| (_| || (_| ||  __/ / . \           | |____ | |____  _| |_       
|______|\__,_| \__, | \___|/_/ \_\           \_____||______||_____| 
		__/ |                                                             
	       |___/                                                              

EdgeX CLI version: 0.0.1
https://www.edgexfoundry.org/

Usage:
  edgex [command]

Which is inconsistent.
### Is this a regression?

No

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by difince** [comment]
Fixed in https://github.com/edgexfoundry-holding/edgex-cli/pull/181
