### ISSUE TITLE
Feature: Support Go 1.12 for consistency across EdgeX 1.0

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry-holding/edgex-cli#18]

**Comment by mkbhanda** [comment]
This might just involve test, and adding to your documentation Go version >= 1.11

**Comment by alexcourouble** [comment]
Currently, both Edinburg and Master branches refer to go 1.11 https://github.com/edgexfoundry/edgex-go#prerequisites

If I remember correctly, Edinburg is under Go 1.11 and Fuji is planned to be under Go 1.12.

Ideally, the CLI should be compatible with both version and thus with both Go 1.11 and 1.12. I'll add that to the README.
