### ISSUE TITLE
version url incorrect

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry-holding/edgex-cli#180]
# 🐞 Bug Report

error ./edgex-cli version 

### Is this a regression?
Yes

Introduced possibly with "Merge pull request #176 from difince/renameClientToRequest"
because  ApiVersionRoute does not include "v1"

// Constants related to defined routes in the service APIs
const (
        ApiVersionRoute            = "/api/version"
        ApiBase                    = "/api/v1"

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by difince** [comment]
https://github.com/edgexfoundry-holding/edgex-cli/blob/4fa34e8ee4a78cc89fbe16ebcdd303f8a577d6df/cmd/version/version.go#L9
By default "Version" variable has value "master"

So, when "version" command is executed in developing mode , via the IDE ..  "master" will be printed out.
If version command is executed by `./edgex-cli version` command  (prior to this build or install is executed) 
the result will come from https://github.com/edgexfoundry-holding/edgex-cli/blob/master/VERSION

How version.go Version variable got the value written in VERSION file - happens here : https://github.com/edgexfoundry-holding/edgex-cli/blob/4fa34e8ee4a78cc89fbe16ebcdd303f8a577d6df/Makefile#L21-L22
"-X github.com/edgexfoundry-holding/edgex-cli/cmd/version.Version=$(VERSION)

I guess that using "master" as a default value is misleading. That is why I would change it to "dev" (stands for development)
