### ISSUE TITLE
Enable specifying EdgeX Host IP address via CLI (flag/ENV/config)

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry-holding/edgex-cli#34]
# 🚀 Feature Request

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
The ability to specify the EdgeX Host IP would enable using CLI against remote EdgeX instances, and allow the user to switch between them. A single context at a time is plenty.  

### Describe alternatives you've considered
Currently the IP addresses hardcoded in the URLs in each command.
Making it configurable through the command line via an initial set command, or through an environment variable or through a config file will ease use.

**Comment by alexcourouble** [comment]
Host configurable from config.
