### ISSUE TITLE
Filter events by device

### ISSUE THREAD

**Issue by alexcourouble** [edgexfoundry-holding/edgex-cli#42]
# 🚀 Feature Request

### Description
Like we talked about, we should be able to looks at the events created by a specific device.
@nkstanchev 

### Describe the solution you'd like
Something along the lines of: `edgex event list [devicename/id]`

### Describe alternatives you've considered
none

**Comment by nkstanchev** [comment]
I'd like to work on this as well

**Comment by alexcourouble** [comment]
it's all yours @nkstanchev !!
