### ISSUE TITLE
List readings command

### ISSUE THREAD

**Issue by alexcourouble** [edgexfoundry-holding/edgex-cli#43]
# 🚀 Feature Request

### Description
Since event can have multiple readings, it would be easier to list the readings in a separate command like: `edgex reading list`. 

In the future, we could list readings for: 
* A specific event
* A specific device
* Any other possible filter allowed by the API

This can be done either through this route: http://localhost:48080/api/v1/reading

Or by iterating over each reading in each event object in this route:  http://localhost:48080/api/v1/event

Want to work on this @nkstanchev? No worries if you have other things on your plate.

**Comment by nkstanchev** [comment]
It's fine. I'll take it
