### ISSUE TITLE
Gracefully fail when CLI is unable to connect to EdgeX

### ISSUE THREAD

**Issue by alexcourouble** [edgexfoundry-holding/edgex-cli#82]
# 🚀 Feature Request

### Description
When trying to run any command while edgex is not running will result in an unhandled error.

### Describe the solution you'd like
Tell user that connection was unsuccessful, probably due to EdgeX not running.

**Comment by mkbhanda** [comment]
Fixed by #146.
Returns after connection timeout with timeout message
